In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [3]:
Results = pd.read_csv("C:/Users/tsswi/OneDrive/Desktop/DU_Classwork/Formula_1_csvs/results.csv/results.csv")
#Qualifying = pd.read_csv("C:/Users/tsswi/OneDrive/Desktop/DU_Classwork/Formula_1_csvs/qualifying.csv")
Pit_stops = pd.read_csv("C:/Users/tsswi/OneDrive/Desktop/DU_Classwork/Formula_1_csvs/pit_stops.csv")
#Race = pd.read_csv("C:/Users/tsswi/OneDrive/Desktop/DU_Classwork/Formula_1_csvs/races.csv")
constructors = pd.read_csv("C:/Users/tsswi/Group-4/Formula_1_csvs/constructors.csv")

In [8]:
constructors.shape

(211, 3)

In [27]:
Results.head(10)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
5,6,18,6,3,8,13,6,6,6,3.0,57,\N,\N,50,14,1:29.639,212.974,11
6,7,18,7,5,14,17,7,7,7,2.0,55,\N,\N,22,12,1:29.534,213.224,5
7,8,18,8,6,1,15,8,8,8,1.0,53,\N,\N,20,4,1:27.903,217.180,5
8,9,18,9,2,4,2,\N,R,9,0.0,47,\N,\N,15,9,1:28.753,215.100,4
9,10,18,10,7,12,18,\N,R,10,0.0,43,\N,\N,23,13,1:29.558,213.166,3

In [10]:
Pit_stops.head()

   raceId  driverId  stop  lap      time duration  milliseconds
0     841       153     1    1  17:05:23   26.898         26898
1     841        30     1    1  17:05:52   25.021         25021
2     841        17     1   11  17:20:48   23.426         23426
3     841         4     1   12  17:22:34   23.251         23251
4     841        13     1   13  17:24:10   23.842         23842

In [31]:
# Merge the two DFs on 'driverId'
#mouse_data_complete = pd.merge(mouse_metadata, study_results, how="outer", on=["Mouse ID", "Mouse ID"])
raw_df = pd.merge(Results, Pit_stops, on =['driverId'], how = 'outer')
raw_df

,resultId,raceId_x,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,rank,fastestLapTime,fastestLapSpeed,statusId,raceId_y,stop,lap,time_y,duration,milliseconds_y
0,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,841.0,1.0,16.0,17:28:24,23.227,23227.0
1,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,841.0,2.0,36.0,17:59:29,23.199,23199.0
2,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,842.0,1.0,12.0,16:24:40,22.552,22552.0
3,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,842.0,2.0,24.0,16:45:48,22.611,22611.0
4,1,18,1,1,22,1,1,1,1,10.0,...,2,1:27.452,218.300,1,842.0,3.0,37.0,17:08:28,25.382,25382.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1692334,25837,1096,855,51,24,15,12,12,12,0.0,...,8,1:29.600,212.183,11,1095.0,1.0,16.0,15:27:16,24.332,24332.0
1692335,25837,1096,855,51,24,15,12,12,12,0.0,...,8,1:29.600,212.183,11,1095.0,2.0,37.0,15:54:45,25.111,25111.0
1692336,25837,1096,855,51,24,15,12,12,12,0.0,...,8,1:29.600,212.183,11,1096.0,1.0,15.0,17:26:28,22.435,22435.0
1692337,25837,1096,855,51,24,15,12,12,12,0.0,...,8,1:29.600,212.183,11,1096.0,2.0,44.0,18:11:10,23.159,23159.0
1692338,25714,1089,856,3,45,8,9,9,9,2.0,...,13,1:26.624,240.750,1,1089.0,1.0,19.0,15:31:43,24.628,24628.0

In [21]:
# We don't need all the drivers, so let's filter by ID's 1052:1073
filtered_raw = raw_df[raw_df['raceId_x'] == 1052| 1053| 1054| 1057| 1058| 1059| 1060| 1061|1062|
                      1063|1064|1065|1066|1067|1068|1069|1070|1071|1072|1073]

In [22]:
filtered_raw

,resultId,raceId_x,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,rank,fastestLapTime,fastestLapSpeed,statusId,raceId_y,stop,lap,time_y,duration,milliseconds_y
141470,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,841.0,1.0,16.0,17:28:24,23.227,23227.0
141471,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,841.0,2.0,36.0,17:59:29,23.199,23199.0
141472,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,842.0,1.0,12.0,16:24:40,22.552,22552.0
141473,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,842.0,2.0,24.0,16:45:48,22.611,22611.0
141474,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,842.0,3.0,37.0,17:08:28,25.382,25382.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1692045,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1094.0,1.0,45.0,15:07:02,24.218,24218.0
1692046,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1095.0,1.0,16.0,15:27:16,24.332,24332.0
1692047,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1095.0,2.0,37.0,15:54:45,25.111,25111.0
1692048,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1096.0,1.0,15.0,17:26:28,22.435,22435.0
1692049,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1096.0,2.0,44.0,18:11:10,23.159,23159.0

Okay, so I merged the two df's I think we will need to answer question one; results and pit stops. However, the raceId columns are different and do not correlate. Do we know which one is the correct column - I've been using the raceId_x because it seems to match up with the ID's that Talon sent us in the Slack chat.

In [26]:
test = filtered_raw[filtered_raw['raceId_x'] == 1087]
test

,resultId,raceId_x,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,rank,fastestLapTime,fastestLapSpeed,statusId,raceId_y,stop,lap,time_y,duration,milliseconds_y
141470,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,841.0,1.0,16.0,17:28:24,23.227,23227.0
141471,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,841.0,2.0,36.0,17:59:29,23.199,23199.0
141472,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,842.0,1.0,12.0,16:24:40,22.552,22552.0
141473,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,842.0,2.0,24.0,16:45:48,22.611,22611.0
141474,25685,1087,1,131,44,4,\N,R,20,0.0,...,0,\N,\N,130,842.0,3.0,37.0,17:08:28,25.382,25382.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1692045,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1094.0,1.0,45.0,15:07:02,24.218,24218.0
1692046,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1095.0,1.0,16.0,15:27:16,24.332,24332.0
1692047,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1095.0,2.0,37.0,15:54:45,25.111,25111.0
1692048,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1096.0,1.0,15.0,17:26:28,22.435,22435.0
1692049,25679,1087,855,51,24,18,14,14,14,0.0,...,9,1:52.317,224.493,1,1096.0,2.0,44.0,18:11:10,23.159,23159.0

I have a bilivit. I wonder what the boys have done.